
package webservice.bean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_HCM20301_JCCRM2ERP_Syn_OutService", targetNamespace = "http://www.gcl-power.com/ERP/HCM", wsdlLocation = "https://crm.gclsi.hk:8089/dir/wsdl?p=ic/88d429edb7c5323692f5481d7206d1f7")
public class SIHCM20301JCCRM2ERPSynOutService
    extends Service
{

    private final static URL SIHCM20301JCCRM2ERPSYNOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIHCM20301JCCRM2ERPSYNOUTSERVICE_EXCEPTION;
    private final static QName SIHCM20301JCCRM2ERPSYNOUTSERVICE_QNAME = new QName("http://www.gcl-power.com/ERP/HCM", "SI_HCM20301_JCCRM2ERP_Syn_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://crm.gclsi.hk:8089/dir/wsdl?p=ic/88d429edb7c5323692f5481d7206d1f7");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIHCM20301JCCRM2ERPSYNOUTSERVICE_WSDL_LOCATION = url;
        SIHCM20301JCCRM2ERPSYNOUTSERVICE_EXCEPTION = e;
    }

    public SIHCM20301JCCRM2ERPSynOutService() {
        super(__getWsdlLocation(), SIHCM20301JCCRM2ERPSYNOUTSERVICE_QNAME);
    }

    public SIHCM20301JCCRM2ERPSynOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIHCM20301JCCRM2ERPSYNOUTSERVICE_QNAME, features);
    }

    public SIHCM20301JCCRM2ERPSynOutService(URL wsdlLocation) {
        super(wsdlLocation, SIHCM20301JCCRM2ERPSYNOUTSERVICE_QNAME);
    }

    public SIHCM20301JCCRM2ERPSynOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIHCM20301JCCRM2ERPSYNOUTSERVICE_QNAME, features);
    }

    public SIHCM20301JCCRM2ERPSynOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIHCM20301JCCRM2ERPSynOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIHCM20301JCCRM2ERPSynOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIHCM20301JCCRM2ERPSynOut getHTTPPort() {
        return super.getPort(new QName("http://www.gcl-power.com/ERP/HCM", "HTTP_Port"), SIHCM20301JCCRM2ERPSynOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIHCM20301JCCRM2ERPSynOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIHCM20301JCCRM2ERPSynOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.gcl-power.com/ERP/HCM", "HTTP_Port"), SIHCM20301JCCRM2ERPSynOut.class, features);
    }

    /**
     * 
     * @return
     *     returns SIHCM20301JCCRM2ERPSynOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIHCM20301JCCRM2ERPSynOut getHTTPSPort() {
        return super.getPort(new QName("http://www.gcl-power.com/ERP/HCM", "HTTPS_Port"), SIHCM20301JCCRM2ERPSynOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIHCM20301JCCRM2ERPSynOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIHCM20301JCCRM2ERPSynOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.gcl-power.com/ERP/HCM", "HTTPS_Port"), SIHCM20301JCCRM2ERPSynOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIHCM20301JCCRM2ERPSYNOUTSERVICE_EXCEPTION!= null) {
            throw SIHCM20301JCCRM2ERPSYNOUTSERVICE_EXCEPTION;
        }
        return SIHCM20301JCCRM2ERPSYNOUTSERVICE_WSDL_LOCATION;
    }

}
